### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (380539,) + inhomogeneous part.

### ISSUE THREAD

**Issue by BEILOP** [yeeeqichen/FTM#1]
```python utils/preprocess_data.py --data reddit --bipartite
Traceback (most recent call last):
  File "utils/preprocess_data.py", line 87, in <module>
    run(args.data, bipartite=args.bipartite)
  File "utils/preprocess_data.py", line 67, in run
    df, feat = preprocess(PATH)
  File "utils/preprocess_data.py", line 36, in preprocess
    'idx': idx_list}), np.array(feat_l)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (380539,) + inhomogeneous part.
```

**Comment by yeeeqichen** [comment]
Can you try directly download the prepocessed data from the link in README?

**Comment by BEILOP** [comment]
是的，我将再次重新下载和上传这部分以排除是否此错误，我是照着readme下载了reddit，
